# yaml-language-server: $schema=https://json.schemastore.org/pre-commit-config.json

# Configuration file for https://pre-commit.com/
#
# Run `pre-commit install` once to install a Git pre-commit hook locally. This will
# ensure that each commit passes the checks before entering the Git history.

default_stages:
  # Prevent that hooks run twice, triggered by both
  # the Git commit-msg and the pre-commit hook.
  - commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-case-conflict
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-toml
      - id: check-xml
      - id: check-yaml
        exclude: ^.*spectral\.yaml$
      - id: destroyed-symlinks
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: ^(ofdb-gateways/src/user_communication/templates/.*\.txt|ofdb-app-clearance/assets/.*)$
      - id: fix-byte-order-marker
      - id: forbid-new-submodules
      - id: mixed-line-ending
      - id: trailing-whitespace
        exclude: ^ofdb-app-clearance/assets/.*$
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v9.11.0
    hooks:
      - id: commitlint
        stages:
          - commit-msg
  - repo: https://github.com/DavidAnson/markdownlint-cli2
    rev: v0.12.1
    hooks:
      - id: markdownlint-cli2
  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.6
    hooks:
      - id: shellcheck
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        args: [--ignore-words=.codespellignore]
        exclude: ^search_results\.json|src/ports/web/frontend/login\.rs|ofdb-gateways/src/user_communication/mod\.rs|doc/c4-plantuml/.*\.puml|Cargo.lock|ofdb-gateways/src/user_communication/templates/.*\.txt|ofdb-core/src/usecases/find_duplicates.rs|ofdb-gateways/src/email/sendmail.rs$
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.27.3
    hooks:
      - id: check-github-actions
      - id: check-github-workflows
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.1.0
    hooks:
      - id: prettier
        types_or:
          - yaml
          - markdown
        exclude: ^ofdb-app-clearance/assets/.*$
  - repo: https://github.com/doublify/pre-commit-rust
    rev: v1.0
    hooks:
      - id: fmt
        args: [--all, --]
      - id: clippy
        args:
          [--locked, --workspace, --all-targets, --no-deps, --, -D, warnings]
  - repo: local
    hooks:
      - id: cargo-doc
        name: cargo-doc
        entry: env RUSTDOCFLAGS=-Dwarnings cargo
        language: system
        pass_filenames: false
        args: [doc, --locked, --workspace, --no-deps]
  - repo: https://github.com/python-openapi/openapi-spec-validator
    rev: 0.7.1
    hooks:
      - id: openapi-spec-validator
