# Intended for local usage for the default target + WASM.
# Must be overridden in CI builds to specify different,
# custom targets!
[toolchain]
channel = "nightly-2021-12-05"
profile = "minimal"
components = [ "rustfmt", "clippy" ]
targets = [ "wasm32-unknown-unknown" ]
