[package]
name = "ofdb-seed"
description = "A seed library for building OpenFairDB based web applications"
version = "0.11.0"
authors = ["slowtec GmbH <post@slowtec.de>"]
license = "MIT/Apache-2.0"
homepage = "https://github.com/kartevonmorgen/openfairdb"
repository = "https://github.com/kartevonmorgen/openfairdb"
edition = "2021"

[dependencies]
ofdb-boundary = { version = "0.11.0", default-features = false }
percent-encoding = "2.1.0"
seed = "0.9.2"
web-sys = "0.3.59"

[badges]
maintenance = { status = "actively-developed" }
