[package]
name = "ofdb-db-sqlite"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.58"
log = "0.4.17"
num-traits = "0.2.15"
diesel = { version = "1.4.8", features = ["sqlite", "r2d2"] }
ofdb-core = { version = "0.0.0", path = "../ofdb-core" }
parking_lot = "0.12.1"
time = { version = "0.3.11", features = ["macros", "formatting", "parsing"] }
