[package]
name = "ofdb-db-sqlite"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.62"
log = "0.4.17"
num-traits = "0.2.15"
diesel = { version = "1.4.8", features = ["sqlite", "r2d2"] }
diesel_migrations = { version = "1.4.0", features = ["sqlite"] }
ofdb-core = { version = "0.0.0", path = "../ofdb-core" }
parking_lot = "0.12.1"
time = { version = "0.3.14", features = ["macros", "formatting", "parsing"] }

# Bundle SQLite code to prevent dynamic linking.
# The pinned version must be compatible with diesel!
libsqlite3-sys = { version = "0.22", features = ["bundled"] }
