[package]
name = "ofdb-app"
version = "0.0.0" # will stay 0.0.0 until published
authors = ["slowtec GmbH <post@slowtec.de>"]
edition = "2021"
publish = false

[dependencies]
async-trait = "0.1.68"
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
gloo-net = { version = "0.2.6", default-features = false }
gloo-storage = "0.2.2"
leptos = { version = "0.2.5", features = ["stable"] }
leptos_router = { version = "0.2.5", features = ["stable", "csr"] }
log = "0.4.17"
percent-encoding = "2.2.0"
serde = "1.0.160"
thiserror = "1.0.40"
wasm-bindgen = "0.2.84"
web-sys = "0.3.61"

[dependencies.ofdb-boundary]
version = "0.12.2"
default-features = false
features = ["extra-derive"]

[patch.crates-io]
ofdb-boundary = { path = "../ofdb-boundary" }

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
