[package]
name = "ofdb-app"
version = "0.0.0" # will stay 0.0.0 until published
authors = ["slowtec GmbH <post@slowtec.de>"]
edition = "2021"
publish = false
rust-version = "1.71.0"

[dependencies]
async-trait = "0.1.71"
console_error_panic_hook = "0.1.7"
console_log = "1.0.0"
gloo-storage = "0.2.2"
leptos = { version = "0.4.3", features = ["csr"] }
leptos_router = { version = "0.4.3", features = ["csr"] }
log = "0.4.19"
percent-encoding = "2.3.0"
serde = "1.0.171"
thiserror = "1.0.43"
wasm-bindgen = "0.2.87"
web-sys = "0.3.64"

# Update to v0.3.x as soon as
# https://github.com/rustwasm/gloo/issues/353
# has been fixed.
[dependencies.gloo-net]
version = "0.2.6"
default-features = false

[dependencies.ofdb-boundary]
version = "0.12.2"
default-features = false
features = ["extra-derive"]

[patch.crates-io]
ofdb-boundary = { path = "../ofdb-boundary" }

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
