[package]
name = "ofdb-db-tantivy"
version = "0.0.0" # will stay 0.0.0 until published

edition.workspace = true
rust-version.workspace = true

[dependencies]
ofdb-core = "=0.0.0"

anyhow = "1.0.86"
log = "0.4.22"
num-traits = "0.2.19"
parking_lot = "0.12.3"
strum = "0.26.3"
tantivy = "0.22.0"
