[package]
name = "ofdb-db-tantivy"
version = "0.0.0"
edition = "2021"

[dependencies]
ofdb-core = "=0.0.0"

anyhow = "1.0.62"
log = "0.4.17"
num-traits = "0.2.15"
parking_lot = "0.12.1"
strum = "0.24.1"
tantivy = "0.18.0"
