[package]
name = "ofdb-application"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
ofdb-core = "=0.0.0"
ofdb-db-sqlite = "=0.0.0" # TODO: remove
ofdb-entities = { version = "0.11.0", features = ["url"] }

anyhow = "1.0.62"
csv = "1.1.6"
log = "0.4.17"
pwhash = "1.0.0"
r2d2 = ">=0.8.10,<0.9" # TODO: remove
serde_json = "1.0.85"
thiserror = "1.0.32"

[dev-dependencies]
ofdb-db-tantivy = "=0.0.0" # TODO: remove
