[package]
name = "ofdb-app-clearance"
version = "0.0.0" # will stay 0.0.0 until published
authors = ["slowtec GmbH <post@slowtec.de>"]
edition = "2021"
publish = false

[dependencies]
# Project dependencies
ofdb-boundary = { version = "0.12.2", features = ["extra-derive"] }
ofdb-entities = "0.12.0"
ofdb-seed = "0.12.2"

# External dependencies
difference = "2.0.0"
seed = "0.9.2"
web-sys = { version = "0.3.60", features = ["HtmlFormElement"] }

[patch.crates-io]
ofdb-boundary = { path = "../ofdb-boundary" }
ofdb-entities = { path = "../ofdb-entities" }
ofdb-seed     = { path = "../ofdb-seed"     }

[profile.release]
lto = true
opt-level = 'z'
codegen-units = 1
