-- Fix millisecond time stamps that have been generated by an early version until 2018-01-19 (1516382882521)
update events set archived=archived/1000 where archived not null and archived>1000000000000;

-- Fix invalid millisecond time stamps that have been accepted before v0.8.0
update events set start=start/1000 where start>1000000000000;
update events set end=end/1000 where end not null and end>1000000000000;

-- Delete invalid tags with less than 2 characters (= empty or single character)
delete from event_tags where length(tag) < 2;
delete from org_tag_relations where length(tag_id) < 2;
delete from place_revision_tag where length(tag) < 2;
delete from tags where length(id) < 2;

-- Delete orphaned tag relations
delete from event_tags where event_id not in (select id from events);
delete from org_tag_relations where org_id not in (select id from organizations);
delete from place_revision_tag where parent_rowid not in (select rowid from place);

-- Insert missing tags (just in case some got lost along the way)
insert or ignore into tags (id) select tag from event_tags;
insert or ignore into tags (id) select tag_id from org_tag_relations;
insert or ignore into tags (id) select tag from place_revision_tag where parent_rowid in (select rowid from place_revision where current_status > 0);
