-- Fix millisecond time stamps that have been generated by an early version until 2018-01-19 (1516382882521)
update events set archived=archived/1000 where archived not null and archived>1000000000000;
update place_rev set created_at=created_at/1000 where created_at>1000000000000;
update place_rating set created_at=created_at/1000 where created_at>1000000000000;
update place_rating set archived_at=archived_at/1000 where archived_at not null and archived_at>1000000000000;
update place_rating_comment set created_at=created_at/1000 where created_at>1000000000000;
update place_rating_comment set archived_at=archived_at/1000 where archived_at not null and archived_at>1000000000000;

-- Delete invalid tags with less than 2 characters (= empty or single character)
delete from event_tags where length(tag) < 2;
delete from org_tag_relations where length(tag_id) < 2;
delete from place_rev_tag where length(tag) < 2;
delete from tags where length(id) < 2;

-- Delete orphaned tag relations
delete from event_tags where event_id not in (select id from events);
delete from org_tag_relations where org_id not in (select id from organizations);
delete from place_rev_tag where place_rev_id not in (select id from place_rev);

-- Insert missing tags (just in case some got lost along the way)
insert or ignore into tags (id) select tag from event_tags;
insert or ignore into tags (id) select tag_id from org_tag_relations;
insert or ignore into tags (id) select tag from place_rev_tag where place_rev_id in (select id from place_rev where status > 0);
