[package]
name = "ofdb-boundary"
description = "Serializable, anemic data structures for accessing the OpenFairDB API in a type-safe manner."
version = "0.10.1"
authors = ["slowtec GmbH <post@slowtec.de>"]
license = "MIT/Apache-2.0"
homepage = "https://github.com/kartevonmorgen/openfairdb"
repository = "https://github.com/kartevonmorgen/openfairdb"
edition = "2018"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
serde = { version = "1", features = ["derive"] }

[dependencies.ofdb-entities]
version = "0.10"
path = "../ofdb-entities"
optional = true

[features]
default = ["entity-conversions"]
extra-derive = []
entity-conversions = ["ofdb-entities"]
wasm-bindgen = ["ofdb-entities/wasm-bindgen"]

[badges]
maintenance = { status = "actively-developed" }
