[package]
name = "ofdb-webserver"
version = "0.0.0"
publish = false
edition.workspace = true
rust-version.workspace = true

[dependencies]
ofdb-application = { version = "=0.0.0" }
ofdb-boundary = { version = "0.12.2", features = ["extra-derive"] }
ofdb-core = "=0.0.0"
ofdb-db-sqlite = "=0.0.0" # TODO: remove
ofdb-db-tantivy = "=0.0.0" # TODO: remove
ofdb-entities = { version = "0.12.0", features = ["url"] }

anyhow = "1.0.71"
base64 = { version = "0.21.2", optional = true }
captcha = "0.0.9"
chrono = { version = "0.4.26", default-features = false }
csv = "1.2.2"
icalendar = "0.15.4"
jsonwebtoken = { version = "8.3.0", optional = true }
lazy_static = "1.4.0"
log = "0.4.19"
maud = { version = "0.25.0", optional = true, features = ["rocket"] }
num-traits = "0.2.15"
parking_lot = "0.12.1"
r2d2 = "0.8.10"
rand = { version = "0.8.5", optional = true }
rust-embed = "6.8.1"
rocket = { version = "0.5.0-rc.3", features = ["secrets", "json"] }
rocket_cors = "0.6.0-alpha2"
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.100"
time = { version = "0.3.23", features = ["macros", "formatting"] }
thiserror = "1.0.43"
uuid = { version = "1.4.0", features = ["v4"] }

[dev-dependencies]
ofdb-entities = { version = "0.12.0", features = ["url", "builders"] }

[build-dependencies]
walkdir = "2.3.3"

[features]
default = ["frontend", "email", "clearance", "cookies", "jwt"]

clearance = []
cookies = []
email = []
frontend = ["maud"]
jwt = ["jsonwebtoken", "base64", "rand"]
