[package]
name = "ofdb-webserver"
version = "0.0.0"
edition = "2021"
publish = false

[dependencies]
ofdb-application = { version = "=0.0.0" }
ofdb-boundary = { version = "=0.10.1", features = ["extra-derive"] }
ofdb-core = "=0.0.0"
ofdb-db-sqlite = "=0.0.0" # TODO: remove
ofdb-db-tantivy = "=0.0.0" # TODO: remove
ofdb-entities = { version = "=0.10.1", features = ["url"] }

anyhow = "1.0.58"
base64 = { version = "0.13.0", optional = true }
captcha = "0.0.9"
csv = "1.1.6"
env_logger = "0.9.0"
jsonwebtoken = { version = "8.1.1", optional = true }
lazy_static = "1.4.0"
log = "0.4.17"
num-traits = "0.2.15"
maud = { version = "0.23.0", optional = true, features = ["rocket"] }
parking_lot = "0.12.1"
rand = { version = "0.8.5", optional = true }
rust-embed = "6.4.0"
rocket = { version = "0.5.0-rc.2", features = ["secrets", "json"] }
rocket_cors = "0.6.0-alpha1"
serde = { version = "1.0.139", features = ["derive"] }
serde_json = "1.0.82"
time = { version = "0.3.11", features = ["macros", "formatting"] }
thiserror = "1.0.31"
uuid = { version = "1.1.2", features = ["v4"] }
r2d2 = "0.8.10"

[dev-dependencies]
ofdb-entities = { version = "=0.10.1", features = ["url", "builders"] }

[build-dependencies]
walkdir = "2.3.2"

[features]
default = ["frontend", "email", "clearance", "cookies", "jwt"]

clearance = []
cookies = []
email = []
frontend = ["maud"]
jwt = ["jsonwebtoken", "base64", "rand"]
