[package]
name = "ofdb-webserver"
version = "0.0.0"
edition = "2021"
publish = false
rust-version = "1.65"

[dependencies]
ofdb-application = { version = "=0.0.0" }
ofdb-boundary = { version = "0.12.2", features = ["extra-derive"] }
ofdb-core = "=0.0.0"
ofdb-db-sqlite = "=0.0.0" # TODO: remove
ofdb-db-tantivy = "=0.0.0" # TODO: remove
ofdb-entities = { version = "0.12.0", features = ["url"] }

anyhow = "1.0.68"
base64 = { version = "0.21.0", optional = true }
captcha = "0.0.9"
chrono = { version = "0.4.23", default-features = false }
csv = "1.1.6"
icalendar = "0.15.1"
jsonwebtoken = { version = "8.2.0", optional = true }
lazy_static = "1.4.0"
log = "0.4.17"
maud = { version = "0.24.0", optional = true, features = ["rocket"] }
num-traits = "0.2.15"
parking_lot = "0.12.1"
r2d2 = "0.8.10"
rand = { version = "0.8.5", optional = true }
rust-embed = "6.4.2"
rocket = { version = "0.5.0-rc.2", features = ["secrets", "json"] }
rocket_cors = "0.6.0-alpha1"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
time = { version = "0.3.17", features = ["macros", "formatting"] }
thiserror = "1.0.38"
uuid = { version = "1.2.2", features = ["v4"] }

[dev-dependencies]
ofdb-entities = { version = "0.12.0", features = ["url", "builders"] }

[build-dependencies]
walkdir = "2.3.2"

[features]
default = ["frontend", "email", "clearance", "cookies", "jwt"]

clearance = []
cookies = []
email = []
frontend = ["maud"]
jwt = ["jsonwebtoken", "base64", "rand"]
