name: Build and upload artifacts

on:
  release:
    types:
      - published
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-and-upload-artifacts:
    name: Building and uploading artifacts
    runs-on: ${{ matrix.runner_os }}
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - x86_64-apple-darwin
          # TODO: Enable Windows
          #- x86_64-pc-windows-msvc
        include:
          - target: x86_64-apple-darwin
            runner_platform: x86_64-apple-darwin
            runner_os: macos-latest
          - target: x86_64-unknown-linux-musl
            runner_platform: x86_64-unknown-linux-gnu
            runner_os: ubuntu-latest
          # TODO: Build on Windows
          #- target: x86_64-pc-windows-msvc
          #  runner_platform: x86_64-pc-windows-msvc
          #  runner_os: windows-latest
          #  executable_suffix: .exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install musl-tools on Linux
        if: matrix.target == 'x86_64-unknown-linux-musl'
        run: |
          sudo apt -y install musl-tools

      # Needed to provide a custom target as input for actions-rs/toolchain
      # that otherwise gets discarded (v1.0.7). The config file only contains
      # a WASM target that interferes with the custom, default target that is
      # defined by the build matrix.
      - name: Delete rust-toolchain.toml on Linux/macOS
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          rm rust-toolchain.toml
      - name: Delete rust-toolchain.toml on Windows
        if: runner.os == 'Windows'
        run: |
          del rust-toolchain.toml

      - name: Install default Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          target: ${{ matrix.target }}
          toolchain: nightly-2021-08-10
          profile: minimal

      - name: Set Rust default toolchain
        run: |
          rustup default nightly-2021-08-10

      - name: Install Rust toolchain for WASM
        uses: actions-rs/toolchain@v1
        with:
          target: wasm32-unknown-unknown
          toolchain: nightly-2021-08-10
          profile: minimal

      - name: Download and install trunk on Linux/macOS
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          wget -qO- https://github.com/thedodd/trunk/releases/download/v0.14.0/trunk-${{ matrix.runner_platform }}.tar.gz | tar -C ~/.cargo/bin -xzf-

      # TODO: Download and install trunk on Windows

      - name: Build ofdb-app-clearance on Linux/macOS
        if: runner.os == 'Linux' || runner.os == 'macOS'
        run: |
          cd ofdb-app-clearance/
          trunk -V
          trunk build

      - name: Build server executable
        run: |
          cargo build --release --target ${{ matrix.target }}

      - name: Upload tagged release artifact
        id: upload-tagged-release-artifact
        # Only triggered by version tags that start with 'v'
        if: startsWith(github.ref, 'refs/tags/v') && startsWith(github.event.release.tag_name, 'v')
        uses: actions/upload-artifact@v2
        with:
          # Artifact is stored and downloaded as .zip archive
          name: openfairdb_${{ github.event.release.tag_name }}_${{ matrix.target }}${{ matrix.executable_suffix }}
          path: target/${{ matrix.target }}/release/openfairdb${{ matrix.executable_suffix }}

      - name: Upload untagged artifact
        if: steps.upload-tagged-release-artifact.outcome == 'skipped'
        uses: actions/upload-artifact@v2
        with:
          # Artifact is stored and downloaded as .zip archive
          name: openfairdb_${{ github.sha }}_${{ matrix.target }}${{ matrix.executable_suffix }}
          path: target/${{ matrix.target }}/release/openfairdb${{ matrix.executable_suffix }}
