name: Continuous integration

on:
  pull_request:
  push:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  continuous-integration:
    name: Building project and running tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        id: checkout
        uses: actions/checkout@v2

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        id: toolchain
        # The inputs should match those in rust-toolchain.toml with the
        # exception of specifying an explicit target for the CI build.
        with:
          toolchain: nightly-2021-08-10
          profile: minimal
          components: rustfmt, clippy

      - name: Install trunk
        run: |
          wget -qO- https://github.com/thedodd/trunk/releases/download/v0.13.1/trunk-x86_64-unknown-linux-gnu.tar.gz | tar -C ~/.cargo/bin -xzf-

      - name: Cache Cargo build artifacts
        id: cache-cargo-build
        uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/bin
            ~/.cargo/registry
            ~/.cargo/git
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ github.head_ref }}-${{ github.run_number }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ github.head_ref }}
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo

      - name: Build ofdb-app-clearance
        run: |
          cd ofdb-app-clearance/
          rustup target add wasm32-unknown-unknown
          trunk -V
          trunk build

      - name: Check ofdb-entities crate
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path ofdb-entities/Cargo.toml

      - name: Check ofdb-core crate
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path ofdb-core/Cargo.toml

      - name: Check ofdb-boundary crate
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path ofdb-boundary/Cargo.toml

      - name: Check ofdb-gateways crate
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path ofdb-gateways/Cargo.toml

      - name: Check ofdb-app-clearance crate
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path ofdb-app-clearance/Cargo.toml

      - name: Test project
        id: test-all
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --workspace --locked

      - name: Build project
        id: build-all
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --locked
