name: Continuous integration

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install system dependencies
        run: |
          sudo apt-get install libsqlite3-dev

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        id: toolchain
        with:
          profile: minimal
          components: rustfmt, clippy

      - name: Install wasm-pack
        uses: actions-rs/install@v0.1
        with:
          crate: wasm-pack
          version: latest
          use-tool-cache: true

      - name: Check ofdb-entities crate
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path ofdb-entities/Cargo.toml

      - name: Check ofdb-core crate
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path ofdb-core/Cargo.toml

      - name: Check ofdb-boundary crate
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path ofdb-boundary/Cargo.toml

      - name: Check ofdb-gateways crate
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path ofdb-gateways/Cargo.toml

      - name: Check ofdb-app-clearance crate
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --manifest-path ofdb-app-clearance/Cargo.toml

      - name: Check code formatting
        id: fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Check for linter warnings
        id: clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: Build project
        id: build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release

      - name: Test project
        id: test
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all

      - name: Cache Cargo build artefacts
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ github.head_ref }}-${{ github.run_number }}
          restore-keys: |
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-${{ github.head_ref }}
            ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
            ${{ runner.os }}-cargo
