# yaml-language-server: $schema=https://json.schemastore.org/github-workflow

name: security-audit

permissions:
  contents: read

on:
  push:
    paths:
      - "**/Cargo.toml"
      - "**/Cargo.lock"
  workflow_dispatch:
  #schedule:
  #  - cron: '0 0 * * *'

jobs:
  security-audit:
    runs-on: ubuntu-latest
    steps:
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable

      - name: Install cargo-audit
        run: |
          cargo install cargo-audit

      - uses: actions/checkout@v3

      - name: Cache Rust toolchain and build artifacts
        uses: Swatinem/rust-cache@v2
        with:
          # Distinguished by the action name to avoid sharing across different actions!
          shared-key: "security-audit"

      - name: Run security audit
        run: |
          cargo audit --deny unsound --deny yanked
