ALTER TABLE comments ADD COLUMN archived INTEGER DEFAULT NULL;
ALTER TABLE entries ADD COLUMN archived INTEGER DEFAULT NULL;
ALTER TABLE events ADD COLUMN archived INTEGER DEFAULT NULL;
ALTER TABLE ratings ADD COLUMN archived INTEGER DEFAULT NULL;